language: node_js

os:
  - windows
node_js: 12

install:
  - |
    if [ $TRAVIS_OS_NAME == "windows" ]; then
      export PATH=$PATH:";C:\Program Files\Git\mingw64\libexec\git-core"
    fi

script:
  - |
    set -e
    echo ">>> Unit test started"
    npm i
    npm t
    echo ">>> Unit test completed"